services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  YolfTypo3\SavLibraryKickstarter\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'    
  
     
